# Generated by Django 4.1.7 on 2023-03-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
